/** Bangladesh: all 64 districts (with Bangla names) and their areas.
    Big cities list their thanas first, then every upazila. Upazila data:
    github.com/nuhil/bangladesh-geocode. Used by checkout and the profile form. */

export const BD_DISTRICTS = ["Bagerhat","Bandarban","Barguna","Barishal","Bhola","Bogra","Brahmanbaria","Chandpur","Chapainawabganj","Chattogram","Chuadanga","Comilla","Cox's Bazar","Dhaka","Dinajpur","Faridpur","Feni","Gaibandha","Gazipur","Gopalganj","Habiganj","Jamalpur","Jashore","Jhalokathi","Jhenaidah","Joypurhat","Khagrachhari","Khulna","Kishoreganj","Kurigram","Kushtia","Lakshmipur","Lalmonirhat","Madaripur","Magura","Manikganj","Meherpur","Moulvibazar","Munshiganj","Mymensingh","Naogaon","Narail","Narayanganj","Narsingdi","Natore","Netrokona","Nilphamari","Noakhali","Pabna","Panchagarh","Patuakhali","Pirojpur","Rajbari","Rajshahi","Rangamati","Rangpur","Satkhira","Shariatpur","Sherpur","Sirajganj","Sunamganj","Sylhet","Tangail","Thakurgaon"];

export const DISTRICT_BN = {"Bagerhat":"বাগেরহাট","Bandarban":"বান্দরবান","Barguna":"বরগুনা","Barishal":"বরিশাল","Bhola":"ভোলা","Bogra":"বগুড়া","Brahmanbaria":"ব্রাহ্মণবাড়িয়া","Chandpur":"চাঁদপুর","Chapainawabganj":"চাঁপাইনবাবগঞ্জ","Chattogram":"চট্টগ্রাম","Chuadanga":"চুয়াডাঙ্গা","Comilla":"কুমিল্লা","Cox's Bazar":"কক্সবাজার","Dhaka":"ঢাকা","Dinajpur":"দিনাজপুর","Faridpur":"ফরিদপুর","Feni":"ফেনী","Gaibandha":"গাইবান্ধা","Gazipur":"গাজীপুর","Gopalganj":"গোপালগঞ্জ","Habiganj":"হবিগঞ্জ","Jamalpur":"জামালপুর","Jashore":"যশোর","Jhalokathi":"ঝালকাঠি","Jhenaidah":"ঝিনাইদহ","Joypurhat":"জয়পুরহাট","Khagrachhari":"খাগড়াছড়ি","Khulna":"খুলনা","Kishoreganj":"কিশোরগঞ্জ","Kurigram":"কুড়িগ্রাম","Kushtia":"কুষ্টিয়া","Lakshmipur":"লক্ষ্মীপুর","Lalmonirhat":"লালমনিরহাট","Madaripur":"মাদারীপুর","Magura":"মাগুরা","Manikganj":"মানিকগঞ্জ","Meherpur":"মেহেরপুর","Moulvibazar":"মৌলভীবাজার","Munshiganj":"মুন্সিগঞ্জ","Mymensingh":"ময়মনসিংহ","Naogaon":"নওগাঁ","Narail":"নড়াইল","Narayanganj":"নারায়ণগঞ্জ","Narsingdi":"নরসিংদী","Natore":"নাটোর","Netrokona":"নেত্রকোণা","Nilphamari":"নীলফামারী","Noakhali":"নোয়াখালী","Pabna":"পাবনা","Panchagarh":"পঞ্চগড়","Patuakhali":"পটুয়াখালী","Pirojpur":"পিরোজপুর","Rajbari":"রাজবাড়ী","Rajshahi":"রাজশাহী","Rangamati":"রাঙ্গামাটি","Rangpur":"রংপুর","Satkhira":"সাতক্ষীরা","Shariatpur":"শরীয়তপুর","Sherpur":"শেরপুর","Sirajganj":"সিরাজগঞ্জ","Sunamganj":"সুনামগঞ্জ","Sylhet":"সিলেট","Tangail":"টাঙ্গাইল","Thakurgaon":"ঠাকুরগাঁও"};

export const AREAS = {
  "Bagerhat": ["Bagerhat Sadar","Chitalmari","Fakirhat","Kachua","Mollahat","Mongla","Morrelganj","Rampal","Sarankhola"],
  "Bandarban": ["Alikadam","Bandarban Sadar","Lama","Naikhongchhari","Rowangchhari","Ruma","Thanchi"],
  "Barguna": ["Amtali","Bamna","Barguna Sadar","Betagi","Pathorghata","Taltali"],
  "Barishal": ["Agailjhara","Babuganj","Bakerganj","Banaripara","Barishal Sadar","Gournadi","Hizla","Mehendiganj","Muladi","Wazirpur","Barisal Sadar"],
  "Bhola": ["Bhola Sadar","Borhan Sddin","Charfesson","Doulatkhan","Lalmohan","Monpura","Tazumuddin"],
  "Bogra": ["Adamdighi","Bogra Sadar","Dhunat","Dhupchanchia","Gabtali","Kahaloo","Nandigram","Sariakandi","Shibganj","Sonatala","Dhunot","Dupchanchia","Nondigram","Shajahanpur","Shariakandi","Sherpur"],
  "Brahmanbaria": ["Akhaura","Ashuganj","Bancharampur","Bijoynagar","Brahmanbaria Sadar","Kasba","Nabinagar","Nasirnagar","Sarail"],
  "Chandpur": ["Chandpur Sadar","Faridgonj","Haimchar","Hajiganj","Kachua","Matlab North","Matlab South","Shahrasti"],
  "Chapainawabganj": ["Bholahat","Chapainawabganj Sadar","Gomostapur","Nachol","Shibganj"],
  "Chattogram": ["Anwara","Banshkhali","Boalkhali","Chandgaon","Double Mooring","Fatikchhari","Hathazari","Khulshi","Kotwali","Mirsarai","Pahartali","Panchlaish","Patiya","Rangunia","Raozan","Satkania","Sitakund","Chandanaish","Karnafuli","Lohagara","Mirsharai","Sandwip","Sitakunda"],
  "Chuadanga": ["Alamdanga","Chuadanga Sadar","Damurhuda","Jibannagar"],
  "Comilla": ["Barura","Brahmanpara","Burichang","Chandina","Chauddagram","Comilla Sadar","Daudkandi","Debidwar","Homna","Laksam","Muradnagar","Nangalkot","Titas","Lalmai","Meghna","Monohargonj","Sadarsouth"],
  "Cox's Bazar": ["Cox's Bazar Sadar","Chakaria","Kutubdia","Maheshkhali","Pekua","Ramu","Teknaf","Ukhia","Coxsbazar Sadar","Eidgaon","Moheshkhali","Ukhiya"],
  "Dhaka": ["Adabor","Badda","Banani","Bangshal","Cantonment","Chawkbazar","Dhanmondi","Demra","Gulshan","Hazaribagh","Jatrabari","Kafrul","Khilgaon","Khilkhet","Kotwali","Lalbagh","Mirpur","Mohammadpur","Motijheel","Mugda","New Market","Pallabi","Paltan","Ramna","Rampura","Sabujbagh","Shah Ali","Shahjahanpur","Shyampur","Tejgaon","Turag","Uttara","Vatara","Dhamrai","Dohar","Keraniganj","Nawabganj","Savar"],
  "Dinajpur": ["Birampur","Birganj","Birol","Bochaganj","Chirirbandar","Dinajpur Sadar","Fulbari","Ghoraghat","Hakimpur","Kaharol","Khansama","Nawabganj","Parbatipur"],
  "Faridpur": ["Alfadanga","Bhanga","Boalmari","Charbhadrasan","Faridpur Sadar","Madhukhali","Nagarkanda","Sadarpur","Saltha"],
  "Feni": ["Chhagalnaiya","Daganbhuiyan","Feni Sadar","Fulgazi","Parshuram","Sonagazi"],
  "Gaibandha": ["Gaibandha Sadar","Gobindaganj","Palashbari","Phulchari","Sadullapur","Saghata","Sundarganj"],
  "Gazipur": ["Gazipur Sadar","Kaliakair","Kaliganj","Kapasia","Sreepur","Tongi"],
  "Gopalganj": ["Gopalganj Sadar","Kashiani","Kotalipara","Muksudpur","Tungipara"],
  "Habiganj": ["Ajmiriganj","Bahubal","Baniachong","Chunarughat","Habiganj Sadar","Lakhai","Madhabpur","Nabiganj"],
  "Jamalpur": ["Bokshiganj","Dewangonj","Islampur","Jamalpur Sadar","Madarganj","Melandah","Sarishabari"],
  "Jashore": ["Abhaynagar","Bagherpara","Chougachha","Jessore Sadar","Jhikargacha","Keshabpur","Manirampur","Sharsha"],
  "Jhalokathi": ["Jhalakathi Sadar","Kathalia","Nalchity","Rajapur"],
  "Jhenaidah": ["Harinakundu","Jhenaidah Sadar","Kaliganj","Kotchandpur","Moheshpur","Shailkupa"],
  "Joypurhat": ["Akkelpur","Joypurhat Sadar","Kalai","Khetlal","Panchbibi"],
  "Khagrachhari": ["Dighinala","Guimara","Khagrachhari Sadar","Laxmichhari","Manikchari","Matiranga","Mohalchari","Panchari","Ramgarh"],
  "Khulna": ["Batiaghata","Dacope","Daulatpur","Dighalia","Dumuria","Khan Jahan Ali","Khulna Sadar","Koyra","Paikgachha","Phultala","Rupsa","Sonadanga","Terokhada","Botiaghata","Dakop","Digholia","Fultola","Paikgasa","Rupsha"],
  "Kishoreganj": ["Austagram","Bajitpur","Bhairab","Hossainpur","Itna","Karimgonj","Katiadi","Kishoreganj Sadar","Kuliarchar","Mithamoin","Nikli","Pakundia","Tarail"],
  "Kurigram": ["Bhurungamari","Charrajibpur","Chilmari","Kurigram Sadar","Nageshwari","Phulbari","Rajarhat","Rowmari","Ulipur"],
  "Kushtia": ["Bheramara","Daulatpur","Khoksa","Kumarkhali","Kushtia Sadar","Mirpur"],
  "Lakshmipur": ["Kamalnagar","Lakshmipur Sadar","Raipur","Ramganj","Ramgati"],
  "Lalmonirhat": ["Aditmari","Hatibandha","Kaliganj","Lalmonirhat Sadar","Patgram"],
  "Madaripur": ["Dasar","Kalkini","Madaripur Sadar","Rajoir","Shibchar"],
  "Magura": ["Magura Sadar","Mohammadpur","Shalikha","Sreepur"],
  "Manikganj": ["Doulatpur","Gior","Harirampur","Manikganj Sadar","Saturia","Shibaloy","Singiar"],
  "Meherpur": ["Gangni","Meherpur Sadar","Mujibnagar"],
  "Moulvibazar": ["Barlekha","Juri","Kamolganj","Kulaura","Moulvibazar Sadar","Rajnagar","Sreemangal"],
  "Munshiganj": ["Gajaria","Louhajanj","Munshiganj Sadar","Sirajdikhan","Sreenagar","Tongibari"],
  "Mymensingh": ["Bhaluka","Dhobaura","Fulbaria","Gafargaon","Gauripur","Haluaghat","Ishwarganj","Muktagachha","Mymensingh Sadar","Nandail","Phulpur","Trishal","Gouripur","Iswarganj","Muktagacha","Tarakanda"],
  "Naogaon": ["Atrai","Badalgachi","Dhamoirhat","Manda","Mohadevpur","Naogaon Sadar","Niamatpur","Patnitala","Porsha","Raninagar","Sapahar"],
  "Narail": ["Kalia","Lohagara","Narail Sadar"],
  "Narayanganj": ["Araihazar","Bandar","Narayanganj Sadar","Rupganj","Sonargaon"],
  "Narsingdi": ["Belabo","Monohardi","Narsingdi Sadar","Palash","Raipura","Shibpur"],
  "Natore": ["Bagatipara","Baraigram","Gurudaspur","Lalpur","Naldanga","Natore Sadar","Singra"],
  "Netrokona": ["Atpara","Barhatta","Durgapur","Kalmakanda","Kendua","Khaliajuri","Madan","Mohongonj","Netrokona Sadar","Purbadhala"],
  "Nilphamari": ["Dimla","Domar","Jaldhaka","Kishorganj","Nilphamari Sadar","Syedpur"],
  "Noakhali": ["Begumganj","Chatkhil","Companiganj","Hatia","Kabirhat","Noakhali Sadar","Senbug","Sonaimori","Subarnachar"],
  "Pabna": ["Atghoria","Bera","Bhangura","Chatmohar","Faridpur","Ishurdi","Pabna Sadar","Santhia","Sujanagar"],
  "Panchagarh": ["Atwari","Boda","Debiganj","Panchagarh Sadar","Tetulia"],
  "Patuakhali": ["Bauphal","Dashmina","Dumki","Galachipa","Kalapara","Mirzaganj","Patuakhali Sadar","Rangabali"],
  "Pirojpur": ["Bhandaria","Kawkhali","Mathbaria","Nazirpur","Nesarabad","Pirojpur Sadar","Zianagar"],
  "Rajbari": ["Baliakandi","Goalanda","Kalukhali","Pangsa","Rajbari Sadar"],
  "Rajshahi": ["Bagha","Bagmara","Boalia","Charghat","Durgapur","Godagari","Matihar","Mohanpur","Paba","Puthia","Rajpara","Shah Makhdum","Tanore","Mohonpur"],
  "Rangamati": ["Baghaichari","Barkal","Belaichari","Juraichari","Kaptai","Kawkhali","Langadu","Naniarchar","Rajasthali","Rangamati Sadar"],
  "Rangpur": ["Badarganj","Gangachara","Kaunia","Mithapukur","Pirgachha","Pirganj","Rangpur Sadar","Taraganj","Badargonj","Pirgacha","Pirgonj","Taragonj"],
  "Satkhira": ["Assasuni","Debhata","Kalaroa","Kaliganj","Satkhira Sadar","Shyamnagar","Tala"],
  "Shariatpur": ["Bhedarganj","Damudya","Gosairhat","Naria","Shariatpur Sadar","Zajira"],
  "Sherpur": ["Jhenaigati","Nalitabari","Nokla","Sherpur Sadar","Sreebordi"],
  "Sirajganj": ["Belkuchi","Chauhali","Kamarkhand","Kazipur","Raigonj","Shahjadpur","Sirajganj Sadar","Tarash","Ullapara"],
  "Sunamganj": ["Bishwambarpur","Chhatak","Derai","Dharmapasha","Dowarabazar","Jagannathpur","Jamalganj","Madhyanagar","Shalla","South Sunamganj","Sunamganj Sadar","Tahirpur"],
  "Sylhet": ["Balaganj","Beani Bazar","Bishwanath","Companiganj","Dakshin Surma","Fenchuganj","Golapganj","Gowainghat","Jaintiapur","Kanaighat","Osmani Nagar","Sylhet Sadar","Zakiganj","Beanibazar","Dakshinsurma","Osmaninagar"],
  "Tangail": ["Basail","Bhuapur","Delduar","Dhanbari","Ghatail","Gopalpur","Kalihati","Madhupur","Mirzapur","Nagarpur","Sakhipur","Tangail Sadar"],
  "Thakurgaon": ["Baliadangi","Haripur","Pirganj","Ranisankail","Thakurgaon Sadar"],
};
